<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Users extends \App\Entity\Users implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Commande' => [parent::class, 'Commande', null],
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'codepostal' => [parent::class, 'codepostal', null],
        "\0".parent::class."\0".'com_users' => [parent::class, 'com_users', null],
        "\0".parent::class."\0".'datenaiss' => [parent::class, 'datenaiss', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'formedeboxe' => [parent::class, 'formedeboxe', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'is_verified' => [parent::class, 'is_verified', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'panier_com' => [parent::class, 'panier_com', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null],
        "\0".parent::class."\0".'resetToken' => [parent::class, 'resetToken', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'sexe' => [parent::class, 'sexe', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        "\0".parent::class."\0".'ville' => [parent::class, 'ville', null],
        'Commande' => [parent::class, 'Commande', null],
        'adresse' => [parent::class, 'adresse', null],
        'codepostal' => [parent::class, 'codepostal', null],
        'com_users' => [parent::class, 'com_users', null],
        'datenaiss' => [parent::class, 'datenaiss', null],
        'email' => [parent::class, 'email', null],
        'formedeboxe' => [parent::class, 'formedeboxe', null],
        'id' => [parent::class, 'id', null],
        'is_verified' => [parent::class, 'is_verified', null],
        'nom' => [parent::class, 'nom', null],
        'panier_com' => [parent::class, 'panier_com', null],
        'password' => [parent::class, 'password', null],
        'photo' => [parent::class, 'photo', null],
        'prenom' => [parent::class, 'prenom', null],
        'resetToken' => [parent::class, 'resetToken', null],
        'roles' => [parent::class, 'roles', null],
        'sexe' => [parent::class, 'sexe', null],
        'telephone' => [parent::class, 'telephone', null],
        'ville' => [parent::class, 'ville', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
